user_token = ""

[channel]
  topic = ""

[filter]
  contact = ""
  email = ""
  limit = ""
  metadata = "info"
  name = ""
  offset = ""
  raw_output = ""

[remotes]
  bootstrap_url = "http://localhost"
  certs_url = "http://localhost"
  http_adapter_url = "http://localhost/http"
  reader_url = "http://localhost"
  things_url = "http://localhost"
  tls_verification = false
  users_url = "http://localhost"
