title = "CLI config file"

#Flags
[[flags]]
token = ""
[remotes]  # root flags
things_url = "http://localhost"
users_url = "http://localhost"
reader_url = "http://localhost"
http_adapter_url = "http://localhost/http"
bootstrap_url = "http://localhost"
certs_url = "http://localhost"

[filter]  # Client
offset = ""
limit = ""
raw_output = ""
name = ""
contact = ""
email = ""
metadata = ""
msg_content_type= ""
tls_verification = "false"

[channel]  # Channel flags
status = ""
state = ""
topic = ""


