title = "CLI config file"

#Flags
[[flags]]
token = ""
[remotes]  # root flags
things_url = "wesmbetes"
users_url = ""
reader_url = ""
http_adapter_url = ""
bootstrap_url = ""
certs_url = ""

[filter]  # Client
offset = ""
limit = "10"
raw_output = "true"
name = ""
contact = ""
email = ""
metadata = ""
msg_content_type= ""
tls_verification = ""

[channel]  # Channel flags
status = ""
state = ""
topic = ""


