title = "CLI config file"

#Flags
[[flags]]
token = ""
[url]  # root flags
ThingsURL = "wesmbetes"
UsersURL = ""
ReaderURL = ""
HTTPAdapterURL = ""
BootstrapURL = ""
CertsURL = ""

[filter]  # Client
Offset = ""
Limit = "10"
RawOutput = "true"
Name = ""
Contact = ""
Email = ""
Metadata = ""
MsgContentType = ""
TLSVerification = ""

[channel]  # Channel flags
Status = ""
State = ""
Topic = ""


