
[channel]
  state = ""
  status = ""
  topic = ""

[filter]
  contact = ""
  email = ""
  limit = ""
  metadata = "info"
  name = "thing_1"
  offset = ""
  raw_output = ""

[remotes]
  bootstrap_url = "http://localhost"
  certs_url = "http://localhost"
  http_adapter_url = "http://localhost/http"
  msg_content_type = "json"
  reader_url = "http://localhost"
  things_url = "http://localhost"
  tls_verification = true
  users_url = "http://localhost"

