#Flags
[[flags]]

[remotes]  # root flags
bootstrap_url = "http://localhost"
certs_url = "http://localhost"
http_adapter_url = "http://localhost/http"
reader_url = "http://localhost"
things_url = "http://localhost"
users_url = "http://localhost"

[filter]  # Client
contact = ""
email = ""
limit = ""
metadata = ""
msg_content_type= ""
name = ""
offset = ""
raw_output = ""
tls_verification = "false"

[channel]  # Channel flags
state = ""
status = ""
topic = ""


