# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.3
info:
  title: Magistrala Activity Log Service
  description: |
    This is the Activity Log Server based on the OpenAPI 3.0 specification.  It is the HTTP API for viewing activity log history. You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    Some useful links:
    - [The Magistrala repository](https://github.com/absmach/magistrala)
  contact:
    email: info@mainflux.com
  license:
    name: Apache 2.0
    url: https://github.com/absmach/magistrala/blob/master/LICENSE
  version: 0.14.0

servers:
  - url: http://localhost:9021
  - url: https://localhost:9021

tags:
  - name: activity-log
    description: Everything about your Activity Log
    externalDocs:
      description: Find out more about Activity Log
      url: http://docs.mainflux.io/

paths:
  /activities:
    get:
      tags:
        - activity-log
      summary: List activity log
      description: |
        Retrieves a list of events. Due to performance concerns, data
        is retrieved in subsets. The API must ensure that the entire
        dataset is consumed either by making subsequent requests, or by
        increasing the subset size of the initial request.
      parameters:
        - $ref: "#/components/parameters/offset"
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/entity_type"
        - $ref: "#/components/parameters/operation"
        - $ref: "#/components/parameters/with_attributes"
        - $ref: "#/components/parameters/with_metadata"
        - $ref: "#/components/parameters/from"
        - $ref: "#/components/parameters/to"
        - $ref: "#/components/parameters/dir"
      security:
        - bearerAuth: []
      responses:
        "200":
          $ref: "#/components/responses/ActivityPageRes"
        "400":
          description: Failed due to malformed query parameters.
        "401":
          description: |
            Missing or invalid access token provided.
            This endpoint is available only for administrators.
        "404":
          description: A non-existent entity request.
        "422":
          description: Database can't process request.
        "500":
          $ref: "#/components/responses/ServiceError"

  /health:
    get:
      summary: Retrieves service health check info.
      tags:
        - health
      responses:
        "200":
          $ref: "#/components/responses/HealthRes"
        "500":
          $ref: "#/components/responses/ServiceError"

components:
  schemas:
    Activity:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: bb7edb32-2eac-4aad-aebe-ed96fe073879
          description: Entity unique identifier.
        operation:
          type: string
          example: users.create
          description: Activity operation.
        occurred_at:
          type: string
          format: date-time
          example: "2024-01-11T12:05:07.449053Z"
          description: Time when the activity occurred.
        payload:
          type: object
          description: Activity payload.
          example:
            {
              "created_at": "2024-01-11T12:05:07.435357Z",
              "metadata": "e30=",
              "name": "Moors-Mlacak",
              "owner": "599a7f51-3f16-41b2-8224-3b1044cea83b",
              "status": "enabled",
            }
      xml:
        name: activity

    ActivityPage:
      type: object
      properties:
        activities:
          type: array
          minItems: 0
          uniqueItems: true
          items:
            $ref: "#/components/schemas/Activity"
        total:
          type: integer
          example: 1
          description: Total number of items.
        offset:
          type: integer
          description: Number of items to skip during retrieval.
        limit:
          type: integer
          example: 10
          description: Maximum number of items to return in one page.
      required:
        - activities
        - total
        - offset

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
      example: { "error": "malformed entity specification" }

    HealthRes:
      type: object
      properties:
        status:
          type: string
          description: Service status.
          enum:
            - pass
        version:
          type: string
          description: Service version.
          example: 0.14.0
        commit:
          type: string
          description: Service commit hash.
          example: 7d6f4dc4f7f0c1fa3dc24eddfb18bb5073ff4f62
        description:
          type: string
          description: Service description.
          example: <service_name> service
        build_time:
          type: string
          description: Service build time.
          example: 1970-01-01_00:00:00

  parameters:
    id:
      name: id
      description: Unique identifier for an entity, e.g. user, group, domain, etc. Used together with entity_type.
      in: query
      schema:
        type: string
        format: uuid
      required: false
      example: bb7edb32-2eac-4aad-aebe-ed96fe073879

    entity_type:
      name: entity_type
      description: Type of entity, e.g. user, group, thing, etc.
      in: query
      schema:
        type: string
        enum:
          - user
          - group
          - thing
      required: false
      example: user

    offset:
      name: offset
      description: Number of items to skip during retrieval.
      in: query
      schema:
        type: integer
        default: 0
        minimum: 0
      required: false
      example: "0"

    limit:
      name: limit
      description: Size of the subset to retrieve.
      in: query
      schema:
        type: integer
        default: 10
        maximum: 10
        minimum: 1
      required: false
      example: "10"

    operation:
      name: operation
      description: Activity operation.
      in: query
      schema:
        type: string
      required: false
      example: users.create

    with_attributes:
      name: with_attributes
      description: Include activity attributes.
      in: query
      schema:
        type: boolean
      required: false
      example: true

    with_metadata:
      name: with_metadata
      description: Include activity metadata.
      in: query
      schema:
        type: boolean
      required: false
      example: true

    from:
      name: from
      description: Start date in unix time.
      in: query
      schema:
        type: string
        format: int64
      required: false
      example: 1966777289

    to:
      name: to
      description: End date in unix time.
      in: query
      schema:
        type: string
        format: int64
      required: false
      example: 1966777289

    dir:
      name: dir
      description: Sort direction.
      in: query
      schema:
        type: string
        enum:
          - asc
          - desc
      required: false
      example: desc

  responses:
    ActivityPageRes:
      description: Data retrieved.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ActivityPage"

    HealthRes:
      description: Service Health Check.
      content:
        application/health+json:
          schema:
            $ref: "#/components/schemas/HealthRes"

    ServiceError:
      description: Unexpected server-side error occurred.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        * User access: "Authorization: Bearer <user_access_token>"

security:
  - bearerAuth: []
