# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional Timescale and Timescale-writer services
# for SuperMQ platform. Since these are optional, this file is dependent of docker-compose file
# from <project_root>/docker. In order to run these services, execute command:
# docker compose -f docker/docker-compose.yml -f docker/addons/timescale-writer/docker-compose.yml up
# from project root. PostgreSQL default port (5432) is exposed, so you can use various tools for database
# inspection and data visualization.

networks:
  supermq-base-net:

volumes:
  supermq-timescale-writer-volume:

services:
  timescale:
    image: timescale/timescaledb:2.13.1-pg16
    container_name: supermq-timescale
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${SMQ_TIMESCALE_PASS}
      POSTGRES_USER: ${SMQ_TIMESCALE_USER}
      POSTGRES_DB: ${SMQ_TIMESCALE_NAME}
    ports:
      - 5433:5432
    networks:
      - supermq-base-net
    volumes:
      - supermq-timescale-writer-volume:/var/lib/timescalesql/data

  timescale-writer:
    image: supermq/timescale-writer:${SMQ_RELEASE_TAG}
    container_name: supermq-timescale-writer
    depends_on:
      - timescale
    restart: on-failure
    environment:
      SMQ_TIMESCALE_WRITER_LOG_LEVEL: ${SMQ_TIMESCALE_WRITER_LOG_LEVEL}
      SMQ_TIMESCALE_WRITER_CONFIG_PATH: ${SMQ_TIMESCALE_WRITER_CONFIG_PATH}
      SMQ_TIMESCALE_WRITER_HTTP_HOST: ${SMQ_TIMESCALE_WRITER_HTTP_HOST}
      SMQ_TIMESCALE_WRITER_HTTP_PORT: ${SMQ_TIMESCALE_WRITER_HTTP_PORT}
      SMQ_TIMESCALE_WRITER_HTTP_SERVER_CERT: ${SMQ_TIMESCALE_WRITER_HTTP_SERVER_CERT}
      SMQ_TIMESCALE_WRITER_HTTP_SERVER_KEY: ${SMQ_TIMESCALE_WRITER_HTTP_SERVER_KEY}
      SMQ_TIMESCALE_HOST: ${SMQ_TIMESCALE_HOST}
      SMQ_TIMESCALE_PORT: ${SMQ_TIMESCALE_PORT}
      SMQ_TIMESCALE_USER: ${SMQ_TIMESCALE_USER}
      SMQ_TIMESCALE_PASS: ${SMQ_TIMESCALE_PASS}
      SMQ_TIMESCALE_NAME: ${SMQ_TIMESCALE_NAME}
      SMQ_TIMESCALE_SSL_MODE: ${SMQ_TIMESCALE_SSL_MODE}
      SMQ_TIMESCALE_SSL_CERT: ${SMQ_TIMESCALE_SSL_CERT}
      SMQ_TIMESCALE_SSL_KEY: ${SMQ_TIMESCALE_SSL_KEY}
      SMQ_TIMESCALE_SSL_ROOT_CERT: ${SMQ_TIMESCALE_SSL_ROOT_CERT}
      SMQ_MESSAGE_BROKER_URL: ${SMQ_MESSAGE_BROKER_URL}
      SMQ_JAEGER_URL: ${SMQ_JAEGER_URL}
      SMQ_JAEGER_TRACE_RATIO: ${SMQ_JAEGER_TRACE_RATIO}
      SMQ_SEND_TELEMETRY: ${SMQ_SEND_TELEMETRY}
      SMQ_TIMESCALE_WRITER_INSTANCE_ID: ${SMQ_TIMESCALE_WRITER_INSTANCE_ID}
    ports:
      - ${SMQ_TIMESCALE_WRITER_HTTP_PORT}:${SMQ_TIMESCALE_WRITER_HTTP_PORT}
    networks:
      - supermq-base-net
    volumes:
      - ./config.toml:/config.toml
