# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional Postgres and Postgres-writer services
# for SuperMQ platform. Since these are optional, this file is dependent of docker-compose file
# from <project_root>/docker. In order to run these services, execute command:
# docker compose -f docker/docker-compose.yml -f docker/addons/postgres-writer/docker-compose.yml up
# from project root. PostgreSQL default port (5432) is exposed, so you can use various tools for database
# inspection and data visualization.

networks:
  supermq-base-net:

volumes:
  supermq-postgres-writer-volume:

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: supermq-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${SMQ_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SMQ_POSTGRES_PASS}
      POSTGRES_DB: ${SMQ_POSTGRES_NAME}
    networks:
      - supermq-base-net
    volumes:
      - supermq-postgres-writer-volume:/var/lib/postgresql/data

  postgres-writer:
    image: supermq/postgres-writer:${SMQ_RELEASE_TAG}
    container_name: supermq-postgres-writer
    depends_on:
      - postgres
    restart: on-failure
    environment:
      SMQ_POSTGRES_WRITER_LOG_LEVEL: ${SMQ_POSTGRES_WRITER_LOG_LEVEL}
      SMQ_POSTGRES_WRITER_CONFIG_PATH: ${SMQ_POSTGRES_WRITER_CONFIG_PATH}
      SMQ_POSTGRES_WRITER_HTTP_HOST: ${SMQ_POSTGRES_WRITER_HTTP_HOST}
      SMQ_POSTGRES_WRITER_HTTP_PORT: ${SMQ_POSTGRES_WRITER_HTTP_PORT}
      SMQ_POSTGRES_WRITER_HTTP_SERVER_CERT: ${SMQ_POSTGRES_WRITER_HTTP_SERVER_CERT}
      SMQ_POSTGRES_WRITER_HTTP_SERVER_KEY: ${SMQ_POSTGRES_WRITER_HTTP_SERVER_KEY}
      SMQ_POSTGRES_HOST: ${SMQ_POSTGRES_HOST}
      SMQ_POSTGRES_PORT: ${SMQ_POSTGRES_PORT}
      SMQ_POSTGRES_USER: ${SMQ_POSTGRES_USER}
      SMQ_POSTGRES_PASS: ${SMQ_POSTGRES_PASS}
      SMQ_POSTGRES_NAME: ${SMQ_POSTGRES_NAME}
      SMQ_POSTGRES_SSL_MODE: ${SMQ_POSTGRES_SSL_MODE}
      SMQ_POSTGRES_SSL_CERT: ${SMQ_POSTGRES_SSL_CERT}
      SMQ_POSTGRES_SSL_KEY: ${SMQ_POSTGRES_SSL_KEY}
      SMQ_POSTGRES_SSL_ROOT_CERT: ${SMQ_POSTGRES_SSL_ROOT_CERT}
      SMQ_MESSAGE_BROKER_URL: ${SMQ_MESSAGE_BROKER_URL}
      SMQ_JAEGER_URL: ${SMQ_JAEGER_URL}
      SMQ_JAEGER_TRACE_RATIO: ${SMQ_JAEGER_TRACE_RATIO}
      SMQ_SEND_TELEMETRY: ${SMQ_SEND_TELEMETRY}
      SMQ_POSTGRES_WRITER_INSTANCE_ID: ${SMQ_POSTGRES_WRITER_INSTANCE_ID}
    ports:
      - ${SMQ_POSTGRES_WRITER_HTTP_PORT}:${SMQ_POSTGRES_WRITER_HTTP_PORT}
    networks:
      - supermq-base-net
    volumes:
      - ./config.toml:/config.toml
